In [3]:
import numpy
import numpy as np
from numpy import*

In [4]:
list = [1,2,3]

In [5]:
type(list)

list

In [18]:
arr = np.array(list)

In [12]:
arr

array([1, 2, 3])

In [19]:
type(arr)

numpy.ndarray

In [20]:
arr.shape

(3,)

In [21]:
arr.ndim

1

In [22]:
arr2 = np.array([3,4,5,6,7,8])

In [23]:
arr2

array([3, 4, 5, 6, 7, 8])

In [24]:
arr2[2:4]

array([5, 6])

In [25]:
arr2[4] = 90

In [26]:
arr2

array([ 3,  4,  5,  6, 90,  8])

In [27]:
list1 = [[1,2,3],[1,3,4],[8,9,0]]

In [28]:
listarr = np.array(list1)

In [29]:
listarr

array([[1, 2, 3],
       [1, 3, 4],
       [8, 9, 0]])

In [30]:
listarr.shape

(3, 3)

In [31]:
listarr.ndim

2

In [35]:
ist1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
listarr=np.array(ist1)


In [36]:
listarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
listarr[0]

array([1, 2, 3, 4, 5])

In [44]:
listarr[: ,3]

array([ 4,  9, 14, 19])

In [45]:
listarr[2:4,2:5]

array([[13, 14, 15],
       [18, 19, 20]])

In [46]:
listarr.diagonal()

array([ 1,  7, 13, 19])

In [49]:
listarr[0,0]

1

In [50]:
listarr[1,2]

8

In [51]:
listarr[2,3]

14

In [53]:
listarr[[0,1,2],[0,2,3]]

array([ 1,  8, 14])

In [54]:
listarr[[0,1,2],[0,2,3]]

array([ 1,  8, 14])

In [61]:
zero = np.zeros((5,5))

In [62]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
one = np.ones((5,4))

In [67]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [78]:
arange = np.arange(20,30)

In [79]:
arange

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [82]:
arange.reshape(5,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [84]:
a = np.arange(16)

In [85]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [87]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [97]:
np.random.rand(2,3)# - [0,1]

array([[0.79551583, 0.30777144, 0.75574281],
       [0.64969075, 0.67485201, 0.83062147]])

In [100]:
p = np.random.randint(1,100,20).reshape(4,5)

In [99]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [101]:
p #original data

array([[93, 81, 74, 91, 98],
       [57, 63, 84, 56, 41],
       [63, 97, 73, 91, 84],
       [55, 18, 29, 87, 59]])

In [102]:
q = p.ravel() # ravel

In [103]:
q

array([93, 81, 74, 91, 98, 57, 63, 84, 56, 41, 63, 97, 73, 91, 84, 55, 18,
       29, 87, 59])

In [104]:
s = p.flatten() #flatten

In [105]:
s

array([93, 81, 74, 91, 98, 57, 63, 84, 56, 41, 63, 97, 73, 91, 84, 55, 18,
       29, 87, 59])

In [106]:
q[1] = 100 #changed the contt in ravel array

In [107]:
q

array([ 93, 100,  74,  91,  98,  57,  63,  84,  56,  41,  63,  97,  73,
        91,  84,  55,  18,  29,  87,  59])

In [108]:
p

array([[ 93, 100,  74,  91,  98],
       [ 57,  63,  84,  56,  41],
       [ 63,  97,  73,  91,  84],
       [ 55,  18,  29,  87,  59]])

In [109]:
s[3] = 500

In [110]:
s

array([ 93,  81,  74, 500,  98,  57,  63,  84,  56,  41,  63,  97,  73,
        91,  84,  55,  18,  29,  87,  59])

In [111]:
p

array([[ 93, 100,  74,  91,  98],
       [ 57,  63,  84,  56,  41],
       [ 63,  97,  73,  91,  84],
       [ 55,  18,  29,  87,  59]])

In [112]:
a = np.arange(9).reshape(3,3)

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
b = np.random.randint(1,10,9).reshape(3,3)

In [116]:
b

array([[5, 7, 9],
       [5, 2, 5],
       [5, 4, 2]])

In [117]:
c = np.concatenate((a,b))

In [118]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [5, 7, 9],
       [5, 2, 5],
       [5, 4, 2]])

In [119]:
d = np.concatenate((a,b),axis = 1)

In [120]:
d

array([[0, 1, 2, 5, 7, 9],
       [3, 4, 5, 5, 2, 5],
       [6, 7, 8, 5, 4, 2]])

In [123]:
s = "heee"
p = "hello"
q =  s+p

In [124]:
q

'heee\nhello'

In [125]:
e = d.transpose()

In [126]:
e

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8],
       [5, 5, 5],
       [7, 2, 4],
       [9, 5, 2]])

In [129]:
p = np.linspace(2,40,8)

In [130]:
p

array([ 2.        ,  7.42857143, 12.85714286, 18.28571429, 23.71428571,
       29.14285714, 34.57142857, 40.        ])

In [131]:
a =  np.arange(16).reshape(4,4)

In [132]:
a #original data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
b = a.ravel() #ravel

In [134]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [135]:
c = a.flatten()#flatten

In [137]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [138]:
b[2] = 89

In [139]:
b

array([ 0,  1, 89,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [140]:
a

array([[ 0,  1, 89,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [141]:
c[4] = 900

In [142]:
c

array([  0,   1,   2,   3, 900,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [143]:
a

array([[ 0,  1, 89,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
import numpy
import numpy as np
from numpy import*


In [145]:
a = arange(16).reshape(4,4)

In [156]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
list = [1,2,3,5.7]

In [149]:
list[2]

3

In [152]:
list[1:3]

[2, 3]

In [158]:
a[2:4,1:4]

array([[ 9, 10, 11],
       [13, 14, 15]])