In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("50_startups.csv")

In [3]:
dataset.head(2)

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['State'] = le.fit_transform(dataset['State'])

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [7]:
x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [9]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [12]:
x_train.shape

(40, 6)

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [14]:
regressor = Sequential()

In [15]:
x_train.shape

(40, 6)

In [20]:
regressor.add(Dense(units = 6,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [21]:
regressor.add(Dense(units = 12,init = 'random_uniform',activation = 'relu')) # 1st hidden layer

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [22]:
regressor.add(Dense(units = 8,init = 'random_uniform',activation = 'relu')) # second hiden layer

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=8, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [23]:
regressor.add(Dense(units = 9,init = 'random_uniform',activation = 'relu')) # third Hidden layer

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [24]:
regressor.add(Dense(units = 1,init = 'random_uniform'))

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
regressor.compile (optimizer = 'adam',loss = 'mse',metrics = ['mse'])

In [34]:
regressor.fit(x_train,y_train , batch_size = 10,epochs = 300)

Epoch 1/300
40/40 [==============================] - 0s 550us/step - loss: 188325166.0000 - mean_squared_error: 188325166.0000
Epoch 2/300
40/40 [==============================] - 0s 400us/step - loss: 186807352.0000 - mean_squared_error: 186807352.0000
Epoch 3/300
40/40 [==============================] - 0s 300us/step - loss: 186883268.0000 - mean_squared_error: 186883268.0000
Epoch 4/300
40/40 [==============================] - 0s 375us/step - loss: 187195854.0000 - mean_squared_error: 187195854.0000
Epoch 5/300
40/40 [==============================] - 0s 350us/step - loss: 186384820.0000 - mean_squared_error: 186384820.0000
Epoch 6/300
40/40 [==============================] - 0s 350us/step - loss: 185146560.0000 - mean_squared_error: 185146560.0000
Epoch 7/300
40/40 [==============================] - 0s 425us/step - loss: 183068146.0000 - mean_squared_error: 183068146.0000
Epoch 8/300
40/40 [==============================] - 0s 350us/step - loss: 185553400.0000 - mean_squared_error:

40/40 [==============================] - 0s 525us/step - loss: 157944160.0000 - mean_squared_error: 157944160.0000
Epoch 65/300
40/40 [==============================] - 0s 350us/step - loss: 159095260.0000 - mean_squared_error: 159095260.0000
Epoch 66/300
40/40 [==============================] - 0s 275us/step - loss: 158047236.0000 - mean_squared_error: 158047236.0000
Epoch 67/300
40/40 [==============================] - 0s 300us/step - loss: 157116424.0000 - mean_squared_error: 157116424.0000
Epoch 68/300
40/40 [==============================] - 0s 425us/step - loss: 158646144.0000 - mean_squared_error: 158646144.0000
Epoch 69/300
40/40 [==============================] - 0s 450us/step - loss: 157640264.0000 - mean_squared_error: 157640264.0000
Epoch 70/300
40/40 [==============================] - 0s 300us/step - loss: 156206460.0000 - mean_squared_error: 156206460.0000
Epoch 71/300
40/40 [==============================] - 0s 475us/step - loss: 158479804.0000 - mean_squared_error: 1584

40/40 [==============================] - 0s 300us/step - loss: 153833202.0000 - mean_squared_error: 153833202.0000
Epoch 128/300
40/40 [==============================] - 0s 375us/step - loss: 151523742.0000 - mean_squared_error: 151523742.0000
Epoch 129/300
40/40 [==============================] - 0s 500us/step - loss: 150562350.0000 - mean_squared_error: 150562350.0000
Epoch 130/300
40/40 [==============================] - 0s 350us/step - loss: 151920602.0000 - mean_squared_error: 151920602.0000
Epoch 131/300
40/40 [==============================] - 0s 550us/step - loss: 150288192.0000 - mean_squared_error: 150288192.0000
Epoch 132/300
40/40 [==============================] - 0s 525us/step - loss: 150827536.0000 - mean_squared_error: 150827536.0000
Epoch 133/300
40/40 [==============================] - 0s 275us/step - loss: 150582922.0000 - mean_squared_error: 150582922.0000
Epoch 134/300
40/40 [==============================] - 0s 450us/step - loss: 149800150.0000 - mean_squared_erro

40/40 [==============================] - 0s 375us/step - loss: 152419908.0000 - mean_squared_error: 152419908.0000
Epoch 191/300
40/40 [==============================] - 0s 350us/step - loss: 148963596.0000 - mean_squared_error: 148963596.0000
Epoch 192/300
40/40 [==============================] - 0s 275us/step - loss: 150382540.0000 - mean_squared_error: 150382540.0000
Epoch 193/300
40/40 [==============================] - 0s 325us/step - loss: 149696086.0000 - mean_squared_error: 149696086.0000
Epoch 194/300
40/40 [==============================] - 0s 450us/step - loss: 149821388.0000 - mean_squared_error: 149821388.0000
Epoch 195/300
40/40 [==============================] - 0s 500us/step - loss: 150662921.0000 - mean_squared_error: 150662921.0000
Epoch 196/300
40/40 [==============================] - 0s 450us/step - loss: 149641304.0000 - mean_squared_error: 149641304.0000
Epoch 197/300
40/40 [==============================] - 0s 375us/step - loss: 150328372.0000 - mean_squared_erro

40/40 [==============================] - 0s 200us/step - loss: 150708156.0000 - mean_squared_error: 150708156.0000
Epoch 254/300
40/40 [==============================] - 0s 250us/step - loss: 149805804.0000 - mean_squared_error: 149805804.0000
Epoch 255/300
40/40 [==============================] - 0s 200us/step - loss: 150657152.0000 - mean_squared_error: 150657152.0000
Epoch 256/300
40/40 [==============================] - 0s 200us/step - loss: 151886888.0000 - mean_squared_error: 151886888.0000
Epoch 257/300
40/40 [==============================] - 0s 325us/step - loss: 152099042.0000 - mean_squared_error: 152099042.0000
Epoch 258/300
40/40 [==============================] - 0s 325us/step - loss: 149058824.0000 - mean_squared_error: 149058824.0000
Epoch 259/300
40/40 [==============================] - 0s 250us/step - loss: 151138424.0000 - mean_squared_error: 151138424.0000
Epoch 260/300
40/40 [==============================] - 0s 225us/step - loss: 150263490.0000 - mean_squared_erro

In [35]:
y_pred = regressor.predict(x_test)

In [36]:
y_pred

array([[118098.83 ],
       [119640.875],
       [125617.17 ],
       [ 60677.92 ],
       [170721.36 ],
       [119837.11 ],
       [ 50282.402],
       [102085.88 ],
       [115817.   ],
       [156484.86 ]], dtype=float32)

In [37]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [38]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [39]:
accuracy

0.7439014076163175

model.save('regressor.h5')

In [40]:
regressor.save('regressor.h5')

In [41]:
x_train.shape

(40, 6)

In [42]:
regressor.predict(np.array([[0,1,0,50000,60000,70000]]))

array([[60624.297]], dtype=float32)