In [1]:
# import the libraries
import pandas as pd
import numpy as np

In [2]:
#step2 - Reading the dataset
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          619    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [6]:
dataset['Geography'].fillna(dataset['Geography'].mode()[0],inplace = True)
dataset['Age'].fillna(dataset['Age'].mean(),inplace = True)
dataset['Balance'].fillna(dataset['Balance'].median(),inplace = True)

In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [8]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          619    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [9]:
p = dataset['Geography'].mode()

In [10]:
p

0    France
dtype: object

In [11]:
p[0]

'France'

In [12]:
dataset['Geography'].mode()[0]

'France'

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Geography'] = le.fit_transform(dataset['Geography'])
# - 0 --some
# - 1 some 
# - 2 somee


In [14]:
dataset['Gender'] = le.fit_transform(dataset['Gender'])

#mee - 1
#female -0



In [15]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          225          2       0   41   
2          3    15619304      Onio          629          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   
5          6    15574012       Chu          645          2       1   44   
6          7    15592531  Bartlett          619          0       1   50   
7          8    15656148    Obinna          376          1       0   29   
8          9    15792365        He          501          0       1   44   
9         10    15592389        H?          684          0       1   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [16]:
x = dataset.iloc[:,3:13].values

In [17]:
y = dataset.iloc[:,13].values

In [18]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [19]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [20]:
type(y)

numpy.ndarray

In [21]:
x.shape

(10000, 10)

In [22]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()






C:\Users\prads\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [23]:
x = np.delete(x,1,axis = 1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [24]:
x = np.concatenate((z,x),axis = 1)

In [25]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [26]:
x.shape

(10000, 12)

In [27]:
y.shape

(10000,)

In [28]:
#split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [29]:
x_test.shape

(2000, 12)

In [30]:
y_test.shape 

(2000,)

In [31]:
x_train.shape 

(8000, 12)

In [32]:
y_train.shape

(8000,)

In [32]:
x_train[:,5:10]

array([[3.4000000e+01, 5.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.2000000e+01, 1.0000000e+00, 7.5681520e+04, 1.0000000e+00,
        1.0000000e+00],
       [2.9000000e+01, 2.0000000e+00, 1.1236734e+05, 1.0000000e+00,
        1.0000000e+00],
       ...,
       [3.5000000e+01, 5.0000000e+00, 1.6127405e+05, 2.0000000e+00,
        1.0000000e+00],
       [3.8000000e+01, 9.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.8000000e+01, 1.0000000e+00, 1.0807633e+05, 1.0000000e+00,
        1.0000000e+00]])

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [38]:
x_train.shape

(8000, 12)

In [36]:
import keras
from keras.layers import Dense
from keras.models import Sequential


Using TensorFlow backend.
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\prads\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [37]:
model = Sequential()

In [39]:
model.add(Dense(units = 12, init = "random_uniform",activation = "relu"))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [40]:
model.add(Dense(units = 24, init = "random_uniform",activation = "relu"))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=24, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [41]:
model.add(Dense(units = 1, init = "random_uniform",activation = "sigmoid"))

C:\Users\prads\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [44]:
model.compile(optimizer = "adam",loss = "binary_crossentropy", metrics = ["accuracy"])


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [45]:
model.fit(x_train,y_train,batch_size = 32 , epochs = 500 )


Epoch 1/100
8000/8000 [==============================] - 3s 404us/step - loss: 0.5161 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 83us/step - loss: 0.4296 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4213 - acc: 0.8147
Epoch 4/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.4150 - acc: 0.8277
Epoch 5/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.4101 - acc: 0.8321
Epoch 6/100
8000/8000 [==============================] - 1s 78us/step - loss: 0.4070 - acc: 0.8335
Epoch 7/100
8000/8000 [==============================] - 1s 83us/step - loss: 0.4042 - acc: 0.8348
Epoch 8/100
8000/8000 [==============================] - 1s 77us/step - loss: 0.4029 - acc: 0.8350
Epoch 9/100
8000/8000 [==============================] - 1s 72us/step - loss: 0.4006 - acc: 0.8365
Epoch 10/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3993 - acc: 0.8363
Epoch 1

8000/8000 [==============================] - 0s 50us/step - loss: 0.3310 - acc: 0.8644
Epoch 81/100
8000/8000 [==============================] - 0s 48us/step - loss: 0.3308 - acc: 0.8631
Epoch 82/100
8000/8000 [==============================] - 0s 50us/step - loss: 0.3310 - acc: 0.8625
Epoch 83/100
8000/8000 [==============================] - 0s 48us/step - loss: 0.3311 - acc: 0.8634
Epoch 84/100
8000/8000 [==============================] - 0s 50us/step - loss: 0.3314 - acc: 0.8639
Epoch 85/100
8000/8000 [==============================] - 0s 48us/step - loss: 0.3305 - acc: 0.8660
Epoch 86/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.3306 - acc: 0.8671
Epoch 87/100
8000/8000 [==============================] - 0s 58us/step - loss: 0.3314 - acc: 0.8642
Epoch 88/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.3314 - acc: 0.8665
Epoch 89/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.3309 - acc: 0.8651
Epoch 90/100


In [46]:
y_pred  = model.predict(x_test)

In [47]:
y_pred

array([[0.26866943],
       [0.34445632],
       [0.05451933],
       ...,
       [0.16910413],
       [0.16399509],
       [0.2202017 ]], dtype=float32)

In [48]:
y_pred = (y_pred > 0.5)

In [49]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [50]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [58]:
y_p = model.predict(sc.transform(([[1,0,0,619,0,42,8,12345,1,1,1,1234567]])))

In [59]:
y_p

array([[0.03462954]], dtype=float32)

In [60]:
y_p = y_p>0.5

In [61]:
y_p

array([[False]])

In [62]:
to increasee the aaccurracy 
add more hidden layers
add more epochs



SyntaxError: invalid syntax (<ipython-input-62-ec7b76e54628>, line 1)

In [63]:
import keras 
keras.__version__

'2.2.4'

In [64]:
import tensorflow 
tensorflow.__version__

'1.14.0'