In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Fish.csv")

In [3]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
data['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
data.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Species'] = le.fit_transform(data['Species'])


In [7]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0          0   242.0     23.2     25.4     30.0  11.5200  4.0200
1          0   290.0     24.0     26.3     31.2  12.4800  4.3056
2          0   340.0     23.9     26.5     31.1  12.3778  4.6961
3          0   363.0     26.3     29.0     33.5  12.7300  4.4555
4          0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154        5    12.2     11.5     12.2     13.4   2.0904  1.3936
155        5    13.4     11.7     12.4     13.5   2.4300  1.2690
156        5    12.2     12.1     13.0     13.8   2.2770  1.2558
157        5    19.7     13.2     14.3     15.2   2.8728  2.0672
158        5    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [8]:
data['Species'].unique()

array([0, 4, 6, 1, 2, 3, 5])

In [9]:
x=data.iloc[:,1:7].values
y=data.iloc[:,0:1].values


In [10]:
x

array([[2.42000e+02, 2.32000e+01, 2.54000e+01, 3.00000e+01, 1.15200e+01,
        4.02000e+00],
       [2.90000e+02, 2.40000e+01, 2.63000e+01, 3.12000e+01, 1.24800e+01,
        4.30560e+00],
       [3.40000e+02, 2.39000e+01, 2.65000e+01, 3.11000e+01, 1.23778e+01,
        4.69610e+00],
       [3.63000e+02, 2.63000e+01, 2.90000e+01, 3.35000e+01, 1.27300e+01,
        4.45550e+00],
       [4.30000e+02, 2.65000e+01, 2.90000e+01, 3.40000e+01, 1.24440e+01,
        5.13400e+00],
       [4.50000e+02, 2.68000e+01, 2.97000e+01, 3.47000e+01, 1.36024e+01,
        4.92740e+00],
       [5.00000e+02, 2.68000e+01, 2.97000e+01, 3.45000e+01, 1.41795e+01,
        5.27850e+00],
       [3.90000e+02, 2.76000e+01, 3.00000e+01, 3.50000e+01, 1.26700e+01,
        4.69000e+00],
       [4.50000e+02, 2.76000e+01, 3.00000e+01, 3.51000e+01, 1.40049e+01,
        4.84380e+00],
       [5.00000e+02, 2.85000e+01, 3.07000e+01, 3.62000e+01, 1.42266e+01,
        4.95940e+00],
       [4.75000e+02, 2.84000e+01, 3.10000e+01, 3.6

In [11]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [12]:
z

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [14]:
y_train.shape

(127, 7)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\prads\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [17]:
model = Sequential()

In [18]:
x_train.shape

(127, 6)

In [19]:
model.add(Dense(units = 6,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [20]:
model.add(Dense(units =9,init = 'random_uniform',activation = 'relu'))

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [21]:
model.add(Dense(units = 7 ,init = 'random_uniform',activation = 'softmax'))

C:\Users\prads\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=7, activation="softmax", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [22]:
model.compile (optimizer = 'adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [23]:
model.fit(x_train,y_train , batch_size = 10,epochs = 300)




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/300
127/127 [==============================] - 1s 7ms/step - loss: 1.9432 - acc: 0.3071
Epoch 2/300
127/127 [==============================] - 0s 275us/step - loss: 1.9355 - acc: 0.4409
Epoch 3/300
127/127 [==============================] - 0s 346us/step - loss: 1.9258 - acc: 0.4488
Epoch 4/300
127/127 [==============================] - 0s 378us/step - loss: 1.9113 - acc: 0.4567
Epoch 5/300
127/127 [==============================] - 0s 401us/step - loss: 1.8894 - acc: 0.4567
Epoch 6/300
127/127 [==============================] - 0s 354us/step - loss: 1.8576 - acc: 0.4724
Epoch 7/300
127/127 [==============================] - 0s 275us/step - loss: 1.8141 - acc: 0.4567
Epoch 8/300
127/127 [==============================] - 0s 283us/step - loss: 1.7628 - acc: 0.4567
Epoch 9/300
127/127 [==============================] - 0s 370us/step - loss: 1.7165 - acc: 0.4567
Epoch 10/300
127/127 [

Epoch 73/300
127/127 [==============================] - 0s 275us/step - loss: 1.2238 - acc: 0.5512
Epoch 74/300
127/127 [==============================] - 0s 291us/step - loss: 1.2176 - acc: 0.5512
Epoch 75/300
127/127 [==============================] - 0s 386us/step - loss: 1.2117 - acc: 0.5591
Epoch 76/300
127/127 [==============================] - 0s 260us/step - loss: 1.2056 - acc: 0.5591
Epoch 77/300
127/127 [==============================] - 0s 252us/step - loss: 1.1998 - acc: 0.5591
Epoch 78/300
127/127 [==============================] - 0s 268us/step - loss: 1.1950 - acc: 0.5591
Epoch 79/300
127/127 [==============================] - 0s 260us/step - loss: 1.1890 - acc: 0.5591
Epoch 80/300
127/127 [==============================] - 0s 252us/step - loss: 1.1813 - acc: 0.5591
Epoch 81/300
127/127 [==============================] - 0s 275us/step - loss: 1.1767 - acc: 0.5591
Epoch 82/300
127/127 [==============================] - 0s 291us/step - loss: 1.1691 - acc: 0.5669
Epoch 83/3

127/127 [==============================] - 0s 252us/step - loss: 0.4441 - acc: 0.8346
Epoch 156/300
127/127 [==============================] - 0s 236us/step - loss: 0.4399 - acc: 0.8346
Epoch 157/300
127/127 [==============================] - 0s 331us/step - loss: 0.4371 - acc: 0.8346
Epoch 158/300
127/127 [==============================] - 0s 346us/step - loss: 0.4347 - acc: 0.8346
Epoch 159/300
127/127 [==============================] - 0s 370us/step - loss: 0.4301 - acc: 0.8346
Epoch 160/300
127/127 [==============================] - 0s 252us/step - loss: 0.4269 - acc: 0.8346
Epoch 161/300
127/127 [==============================] - 0s 370us/step - loss: 0.4249 - acc: 0.8346
Epoch 162/300
127/127 [==============================] - 0s 323us/step - loss: 0.4231 - acc: 0.8346
Epoch 163/300
127/127 [==============================] - 0s 268us/step - loss: 0.4192 - acc: 0.8346
Epoch 164/300
127/127 [==============================] - 0s 315us/step - loss: 0.4170 - acc: 0.8425
Epoch 165/300


127/127 [==============================] - 0s 189us/step - loss: 0.2944 - acc: 0.8661
Epoch 237/300
127/127 [==============================] - 0s 260us/step - loss: 0.2942 - acc: 0.8661
Epoch 238/300
127/127 [==============================] - 0s 346us/step - loss: 0.2937 - acc: 0.8661
Epoch 239/300
127/127 [==============================] - 0s 260us/step - loss: 0.2918 - acc: 0.8819
Epoch 240/300
127/127 [==============================] - 0s 275us/step - loss: 0.2919 - acc: 0.8819
Epoch 241/300
127/127 [==============================] - 0s 260us/step - loss: 0.2906 - acc: 0.8740
Epoch 242/300
127/127 [==============================] - 0s 260us/step - loss: 0.2880 - acc: 0.8740
Epoch 243/300
127/127 [==============================] - 0s 244us/step - loss: 0.2885 - acc: 0.8740
Epoch 244/300
127/127 [==============================] - 0s 291us/step - loss: 0.2866 - acc: 0.8740
Epoch 245/300
127/127 [==============================] - 0s 331us/step - loss: 0.2865 - acc: 0.8740
Epoch 246/300


In [57]:
y_pred = model.predict_classes(x_test)

In [58]:
y_pred

array([0, 4, 2, 4, 2, 2, 6, 3, 0, 2, 2, 3, 6, 2, 4, 2, 2, 3, 2, 0, 4, 6,
       2, 3, 4, 0, 0, 4, 6, 5, 0, 2], dtype=int64)

In [29]:
data.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0        0   242.0     23.2     25.4     30.0   11.52   4.02

In [52]:
y_p = model.predict_classes(sc.transform([[1100,40.1,43,45.5,12.5125,7.4165]]))

In [53]:
y_p[0]

2

In [59]:
index = ['Bream', 'Parkki','Perch','Pike','Roach', 'Smelt','Whitefish']

In [60]:
class1 = index[y_p[0]]

In [61]:
class1

'Perch'

object detection using CNN
collect 5 classes of any objects and apply cnn
pen bottle book chair tabel